branches:
  only:
  - master
language: ruby
rvm:
- 1.9.3
before_script:
- git config --global user.name "Teracy Bot"
- git config --global user.email "teracy.com@gmail.com"
- export REPO_URL="https://$GH_TOKEN@github.com/$GH_REPO.git"
- bundle exec rake setup_github_pages[$REPO_URL]
- git checkout -- _config.yml
script: bundle exec rake generate
after_script:
- bundle exec rake deploy
env:
  global:
  - GH_REPO="teracyhq/blog"
  - secure: ll0qKyaIMGw5Fw+CXNKUE5Afy9zNdQimJHLoyNKi8TzIBFgwyARq/IrTllxA+NTdSWoIGnfV1HHtEbpwbaYlwA+/HxbxGqTza995N8V1llEfp0m1E63dh3qfbKcvJ9Xhg6502VMeXyTYPKAK4nAl2FW4BVhwIrCOTfN1U4oseu8=
notifications:
  slack:
    on_pull_requests: false
    secure: KTgEd5QGsr2HIwSQRkwryoyQZqL1d/D/EysniwUgRO89MP3sGu/6rC6FVXFHI3//s7rm8MWCoX+USfQffp9JtipxD95LRsGCF+0s51M1RF76wfW65IJJe+OFOB0r99lZmjk2oOI7dxy+BJ288+Cnz6jzmPm/jHxlS9/MPktwUKg=
