branches:
  only:
  - master
language: ruby
rvm:
- 1.9.3
before_script:
- git config --global user.name "Teracy Bot"
- git config --global user.email "teracy.com@gmail.com"
- export REPO_URL="https://$GH_TOKEN@github.com/$GH_REPO.git"
- bundle exec rake setup_github_pages[$REPO_URL]
- git checkout -- _config.yml
script: bundle exec rake generate
after_script:
- bundle exec rake deploy
env:
  global:
  - GH_REPO="teracyhq/blog"
  - secure: ll0qKyaIMGw5Fw+CXNKUE5Afy9zNdQimJHLoyNKi8TzIBFgwyARq/IrTllxA+NTdSWoIGnfV1HHtEbpwbaYlwA+/HxbxGqTza995N8V1llEfp0m1E63dh3qfbKcvJ9Xhg6502VMeXyTYPKAK4nAl2FW4BVhwIrCOTfN1U4oseu8=
notifications:
  slack:
    on_success: change
    on_failure: always
    on_pull_requests: false
    rooms:
      secure: QvNDAD9xAorQ42+PbdzdRukaGJXYPmrqiGtiAjucBNNG5aRVXzh22vT7m1Y9SJGkX3c5hKjM68gDwlIjqTMLzCWYkSkW+NgEvIE1rRxFPBtCXNd1jDX4MtmRDP63G2tnqdtIl+S74vRdU2jL8E5bvjZL5NYtVbeCcgPAg/E/clA=
