---
branches:
    only:
    - master
# if your page is user/ organization page, enable source branch and disable master branch build
#   - source
language: ruby
rvm:
  - 1.9.3
before_script:
- git config --global user.name "Hoat Le"
- git config --global user.email "hoatlevan@gmail.com"
- export REPO_URL="https://$GH_TOKEN@github.com/$GH_REPO.git"
- rake setup_github_pages[$REPO_URL]
# To reset the 'url' to the custom domain in '_config.yml'
- git checkout -- _config.yml
script: bundle exec rake generate
after_script:
- bundle exec rake deploy
env:
    global:
    - GH_REPO="teracy-official/teracy-official-blog"
    - secure: "Poaz23pXE+oWJRtC2AGXPFc3945d1RiIJt5yF0M4tBpBBwfK+h5zSFdmtCNrFlSByAsK3c3XUquSE30sj0t32Id3gplSQghH56yR9vJqMABux+RAbKfPz7ptF73khncObjtbP/Oo9EaXdt4/qT40eLHRPpZLBiZ2CMPUT/Rf/vw="
